name: eldlich_golden_lord
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  data_table_2: ^2.3.6
  extended_masked_text: ^2.3.1
  finance:
    git:
      url: https://github.com/yuvaraja2303/finance/
      ref: patch-1
  flutter_form_builder: ^7.5.0
  flutter_localizations:
    sdk: flutter
  font_awesome_flutter: ^10.1.0
  form_builder_extra_fields: ^8.3.0
  form_builder_file_picker: ^2.3.0
  form_builder_image_picker: ^3.1.0
  form_builder_phone_field: ^1.3.0
  form_builder_validators: ^8.3.0
  get:
    git:
      url: https://github.com/jonataslaw/getx
      ref: master
  intl: ^0.17.0
  google_fonts: ^3.0.1
  responsive_framework: ^0.2.0

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
